# --- Execution Setup ---
# Options: chrome, firefox, edge
browser=chrome
headless=false

# --- Environment ---
baseUrl=https://shivprasadl.github.io/my-first-website/

# --- Timeouts (in seconds) ---
implicitWait=10
explicitWait=15

# --- Reporting ---
screenshotOnFailure=true
